use std::env;
use std::fs;
use std::path::Path;

fn optional_const(name: &str, value: Option<String>) -> String {
    match value.filter(|v| !v.is_empty()) {
        Some(v) => format!("pub const {name}: Option<&str> = Some({v:?});"),
        None => format!("pub const {name}: Option<&str> = None;"),
    }
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let manifest_path = Path::new(&manifest_dir);
    let desktop_env = manifest_path.join("..").join(".env");

    if desktop_env.exists() {
        println!("cargo:rerun-if-changed={}", desktop_env.display());
        dotenvy::from_path(&desktop_env).ok();
    }

    let pubkey_path = manifest_path.join("keys").join("memorafy.key.pub");
    let updater_pubkey = fs::read_to_string(&pubkey_path)
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());

    if pubkey_path.exists() {
        println!("cargo:rerun-if-changed={}", pubkey_path.display());
    }

    let embedded = format!(
        "// @generated by build.rs — compile-time config for release builds\n\
         {}\n\
         {}\n\
         {}\n",
        optional_const("SUPABASE_URL", env::var("SUPABASE_URL").ok()),
        optional_const("SUPABASE_ANON_KEY", env::var("SUPABASE_ANON_KEY").ok()),
        optional_const("UPDATER_PUBKEY", updater_pubkey),
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("embedded_config.rs"), embedded).expect("write embedded_config.rs");

    if let Some(pubkey) = fs::read_to_string(&pubkey_path)
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
    {
        let config = serde_json::json!({
            "plugins": {
                "updater": {
                    "pubkey": pubkey
                }
            }
        });
        env::set_var("TAURI_CONFIG", config.to_string());
    }

    tauri_build::build()
}
